import os
import json
import argparse
import sys
from datetime import datetime

try:
    import opentimelineio as otio
except ImportError:
    print("Error: The 'opentimelineio' library is required for this script.")
    print("Please install it by running: pip install opentimelineio")
    sys.exit(1)

def create_resolve_timeline(json_data, videos_dir, output_path, frame_rate=24.0, default_clip_duration=4.0):
    """
    Converts a JSON cut list into a DaVinci Resolve compatible FCPXML timeline.

    Args:
        json_data (dict): The decision JSON from the DirectorAgent node.
        videos_dir (str): Path to the directory containing video files (e.g., render_Style_A.mp4).
        output_path (str): The path to save the output .fcpxml file.
        frame_rate (float): The frame rate of the timeline.
        default_clip_duration (float): Default duration in seconds for the last clip.
    """
    print(f"Initializing timeline with frame rate: {frame_rate} fps.")
    timeline = otio.schema.Timeline(name=f"AI_Director_Timeline_{datetime.now():%Y%m%d_%H%M}")
    track = otio.schema.Track(name="V1", kind=otio.schema.TrackKind.Video)
    timeline.tracks.append(track)

    cuts = json_data.get("cuts")
    if not cuts:
        print("Error: JSON data does not contain a 'cuts' list.")
        return

    # Sort cuts by timestamp to ensure chronological order
    cuts = sorted(cuts, key=lambda x: x["timestamp"])
    print(f"Found {len(cuts)} cuts in the JSON file.")

    # Create a map of style names to video file paths
    video_files = {
        os.path.splitext(f)[0].replace("render_", ""): os.path.join(videos_dir, f)
        for f in os.listdir(videos_dir)
        if f.startswith("render_") and f.lower().endswith((".mp4", ".mov", ".mkv"))
    }
    print(f"Found video files for styles: {list(video_files.keys())}")

    for i, cut in enumerate(cuts):
        start_time_sec = float(cut["timestamp"])
        style = cut["style"]

        # Determine the duration of the clip
        if i + 1 < len(cuts):
            end_time_sec = float(cuts[i + 1]["timestamp"])
            duration_sec = end_time_sec - start_time_sec
        else:
            # This is the last clip, use a default duration
            duration_sec = default_clip_duration
        
        if duration_sec <= 0:
            print(f"Warning: Skipping clip for style '{style}' at {start_time_sec}s due to zero or negative duration.")
            continue

        video_path = video_files.get(style)
        if not video_path:
            print(f"Warning: No video file found for style '{style}'. Skipping this cut.")
            continue

        print(f"Adding clip: Style='{style}', Start={start_time_sec:.2f}s, Duration={duration_sec:.2f}s, File='{os.path.basename(video_path)}'")

        # Create a media reference to the video file
        media_ref = otio.schema.ExternalReference(
            target_url=otio.url_from_path(video_path)
        )

        # Define the source range of the clip from the beginning of the file
        source_range = otio.opentime.TimeRange(
            start_time=otio.opentime.RationalTime(0, frame_rate), # Always start from the beginning of the source file
            duration=otio.opentime.RationalTime.from_seconds(duration_sec, frame_rate)
        )

        # Create the clip and add it to the track
        clip = otio.schema.Clip(
            name=os.path.basename(video_path),
            media_reference=media_ref,
            source_range=source_range
        )
        track.append(clip)

    print(f"\nTimeline creation complete. Total clips added: {len(track)}")
    
    # Export the timeline to FCPXML (Resolve friendly)
    try:
        otio.adapters.write_to_file(timeline, output_path, adapter_name="fcpx_xml")
        print(f"Successfully saved DaVinci Resolve timeline to: {output_path}")
    except Exception as e:
        print(f"Error: Failed to write FCPXML file. {e}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert DirectorAgent JSON to a DaVinci Resolve timeline (FCPXML).",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "json_file",
        help="Path to the input JSON file generated by the DirectorAgent node."
    )
    parser.add_argument(
        "videos_dir",
        help="Path to the directory containing the rendered video files (e.g., 'render_Style_A.mp4')."
    )
    parser.add_argument(
        "-o", "--output",
        default="output_timeline.fcpxml",
        help="Path to save the output .fcpxml file. (Default: output_timeline.fcpxml)"
    )
    parser.add_argument(
        "-fr", "--frame_rate",
        type=float,
        default=24.0,
        help="Frame rate for the timeline. (Default: 24.0)"
    )
    parser.add_argument(
        "-d", "--duration",
        type=float,
        default=4.0,
        help="Default duration in seconds for the final clip in the timeline. (Default: 4.0)"
    )

    args = parser.parse_args()

    if not os.path.exists(args.json_file):
        print(f"Error: Input JSON file not found at '{args.json_file}'")
        sys.exit(1)

    if not os.path.isdir(args.videos_dir):
        print(f"Error: Videos directory not found at '{args.videos_dir}'")
        sys.exit(1)

    try:
        with open(args.json_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError:
        print(f"Error: Failed to parse JSON from '{args.json_file}'. The file may be corrupt or not valid JSON.")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

    create_resolve_timeline(data, args.videos_dir, args.output, args.frame_rate, args.duration)


if __name__ == "__main__":
    main()
